## other configuration excluded from example...
exclude_patterns:
- "docs/"
- "Composer_Docs/"
- "assets/"
- "Chapter13/cs-offerings/"
- "Chapter13/Documentation/"
- "Chapter13/startup/"
- "Chapter13/HTML/fonts/"
- "Chapter13/HTML/js-utils/"
- "Chapter13/network/test/"